name: Actions Workflow

on : [push]

jobs : 
  run-github-actions:
    runs-on : ubuntu-latest
    steps:
      - name: Simple Js Action
        uses: actions/hello-world-javascript-action@main
        with : 
          who-to-greet: 'MOHAMMAD'